### ISSUE TITLE
when click back from settings url, should dismiss setting pane

### ISSUE THREAD

**Issue by hcientist** [VT-TLOS/YouScriber#29]
perhaps we eventually do somethign like notice if they've made changes they didn't save as in http://stackoverflow.com/q/26161854/1449799

**Comment by hcientist** [comment]
this might help: http://stackoverflow.com/questions/24713242/using-ui-router-with-bootstrap-ui-modal

**Comment by Tav0** [comment]
Fixed issue when click back from settings url, should dismiss setting pane #29
